# Probability Practices in Python

### Table of Contents

- [Simulating Coins Flipping Using `np.random.randint` and `np.random.choice()`](#simCoinFlip)

## Simulating Coins Flipping Using `np.random.randint` and `np.random.choice()`

In [3]:
# outcome of one coin flip
np.random.randint(2)

0

In [5]:
# outcomes of ten thousand coin flips
np.random.randint(2, size=10000)

array([0, 0, 1, ..., 1, 1, 0])

In [6]:
# mean outcome of ten thousand coin flips
np.random.randint(2, size=10000).mean()

0.4953

In [17]:
# outcome of one coin flip
np.random.choice([0, 1])

0

In [19]:
# outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000)

array([0, 1, 0, ..., 1, 1, 0])

In [21]:
# mean outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000).mean()

0.4972

In [23]:
# outcomes of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2])

array([1, 1, 1, ..., 0, 1, 0])

In [24]:
# mean outcome of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2]).mean()

0.2002