# Probability Practices in Python

### Table of Contents

- [Simulating Coins Flipping Using `np.random.randint` and `np.random.choice()`](#simCoinFlip)
- [Coin Flips and Die Rolls](#CoinFlips&DieRolls)

<a id=simCoinFlip></a>
## Simulating Coins Flipping Using `np.random.randint` and `np.random.choice()`

In [3]:
# outcome of one coin flip
np.random.randint(2)

0

In [5]:
# outcomes of ten thousand coin flips
np.random.randint(2, size=10000)

array([0, 0, 1, ..., 1, 1, 0])

In [6]:
# mean outcome of ten thousand coin flips
np.random.randint(2, size=10000).mean()

0.4953

In [17]:
# outcome of one coin flip
np.random.choice([0, 1])

0

In [19]:
# outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000)

array([0, 1, 0, ..., 1, 1, 0])

In [21]:
# mean outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000).mean()

0.4972

In [23]:
# outcomes of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2])

array([1, 1, 1, ..., 0, 1, 0])

In [24]:
# mean outcome of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2]).mean()

0.2002

<a id=CoinFlips&DieRolls></a>
## Coin Flips and Die Rolls

### Tasks
- Two fair coin flips produce exactly two heads
- Three fair coin flips produce exactly one head
- Three biased coin flips with P(H) = 0.6 produce exactly one head
- A die rolls an even number
- Two dice roll a double

### 1. Two fair coin flips produce exactly two heads

In [58]:
# simulate 1 million tests of two fair coin flips
tests = np.random.randint(2, size=(int(1e6), 2))
print("The first 5 simulation results: {}".format(tests[:5]))

# sums of all tests
test_sums = tests.sum(axis=1)
print("The first 5 summation: {}".format(test_sums[:5]))

# proportion of tests that produced exactly two heads
prop_result = (test_sums == 0).mean()
print("The proportion of tests that produced exactly two heads is : {}".format(prop_result))

The first 5 simulation results: [[0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 1]]
The first 5 summation: [0 1 1 2 1]
The proportion of tests that produced exactly two heads is : 0.249682


### 2. Three fair coin flips produce exactly one head

In [39]:
# simulate 1 million tests of three fair coin flips
tests = np.random.choice([0, 1], size=(int(1e6), 3))

# sums of all tests
tests_sum = tests.sum(axis=1)

# proportion of tests that produced exactly one head
(tests_sum == 2).mean()

0.374825

### 3. Three biased coin flips with P(H) = 0.6 produce exactly one head

In [40]:
# simulate 1 million tests of three biased coin flips
tests = np.random.choice([0, 1], size=(int(1e6), 3), p=[.6, .4])

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly one head
(test_sums == 2).mean()

0.287707

### 4. A die rolls an even number

In [57]:
# simulate 1 million tests of one die roll
tests = np.random.choice(range(1, 7), size=int(1e6))

# proportion of tests that produced an even number
(tests % 2 == 0).mean()

0.4996

### 5. Two dice roll a double

In [47]:
# simulate the first million die rolls
# first = np.random.choice(range(1, 7), size=(int(1e6), 2))
first = np.random.choice(range(1, 7), size=int(1e6))

# simulate the second million die rolls
second = np.random.choice(range(1, 7), size=int(1e6))

# proportion of tests where the 1st and 2nd die rolled the same number
(first == second).mean()

0.16654